aspnet31/Controllers/LatihanController.cs
using Microsoft.AspNetCore.Mvc;

namespace aspnet31.Controllers
{
    public class LatihanController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

aspnet31/Controllers/ProductController.cs
using aspnet31.Models;
using aspnet31.Repositories.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Net.Http;
using System.Threading.Tasks;

namespace aspnet31.Controllers
{
    public class ProductController : Controller
    {
        ProductRepository productRepository;
        SupplierRepository supplierRepository;

        public ProductController(ProductRepository productRepository, SupplierRepository supplierRepository)
        {
            this.productRepository = productRepository;
            this.supplierRepository = supplierRepository;
        }

        #region get
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        #endregion get

        #region GetbyJson
        [HttpGet]
        public ActionResult GetJson()
        {
            var products = productRepository.Get();
            if (products != null)
                return Ok(new
                {
                    status = 200,
                    message = "Data Berhasil Didapatkan",
                    data = products
                });
            return NotFound(new
            {
                status = 404,
                message = "Data Tidak Ditemukan di getbyjson"
            });
        }
        #endregion GetbyJson

        #region Details
        [HttpGet("/Product/Details/{id}")]
        public ActionResult Details(int id)
        {
            var products = productRepository.Get(id);
            if (products != null)
            {
                return Ok(new
                {
                    status = 200,
                    message = "Data Berhasil Didapatkan",
                    data = products
                });
            }
            else
            {
                return NotFound(new
                {
                    status = 404,
                    message = "Data Tidak Ditemukan didetails"
                });
            }
        }
        #endregion Details

        #region Create
        public ActionResult Create()
        {
            var suppliers = supplierRepository.Get();
            if (suppliers.Count > 0)
            {
                ViewBag.Suppliers = new SelectList(suppliers, "Id", "Name");
            }
            return View();
        }


        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create([FromBody]Product product)
        {
            if (ModelState.IsValid)
            {
                var result = productRepository.Post(product);
                if (result > 0)
                {
                    return Ok(new
                    {
                        status = 200,
                        message = "Dapat Berhasil Diinputkan"
                    });
                }
                else
                {
                    return BadRequest(new
                    {
                        status = 400,
                        message = "Data Gagal Diinputkan"
                    });
                }
            }
            return RedirectToAction("Index", "Home");
        }
        #endregion Create

        #region Edit
        [HttpGet("/Product/Edit/{id}")]
        public ActionResult Edit(int id)
        {
            var suppliers = supplierRepository.Get();
            if (suppliers.Count > 0)
            {
                ViewBag.Suppliers = new SelectList(suppliers, "Id", "Name");
            }
            var products = productRepository.Get(id);
            return View(products);
        }

        [HttpPut]
        //[ValidateAntiForgeryToken]
        public ActionResult Edit([FromBody]Product product)
        {
            if (ModelState.IsValid)
            {
                var result = productRepository.Put(product);
                if (result > 0)
                {
                    return Ok(new
                    {
                        status = 200,
                        message = "Dapat Berhasil DiUpdate"
                    });
                }
                else
                {
                    return BadRequest(new
                    {
                        status = 400,
                        message = "Data Gagal Diinputkan"
                    });
                }
            }
            return RedirectToAction("Index", "Home");
        }
        #endregion Edit

        #region Delete
        [HttpGet("Product/Delete/{id}")]
        public ActionResult Delete(int id)
        {
            var products = productRepository.Get(id);
            if (products != null)
            {
                return View(products);
            }
            return View();
        }

        [HttpDelete]
        //[ValidateAntiForgeryToken]
        public ActionResult Delete([FromBody]Product product)
        {
            var result = productRepository.Delete(product.Id);
            if (result > 0)
            {
                return Ok(new
                {
                    status = 200,
                    message = "Dapat Berhasil Dihapus"
                });
            }
            else
            {
                return BadRequest(new
                {
                    status = 400,
                    message = "Data Gagal Diinputkan"
                });
            }
        }
        #endregion Delete
    }
}

aspnet31/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - First ASP .NET</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/2.2.3/css/buttons.dataTables.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/latihan.css" />
</head>
<style>
    .footer {
    width: 100%;
    font-size: 14px;
    border-top: 1px solid rgba(0,0,0,0.1);
    background: #553C18
;
}
</style>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item"> 
                            <a class="nav-link text-light" asp-area="" asp-controller="Supplier" asp-action="Index">Supplier</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Latihan" asp-action="Index">Latihan</a>
                        </li>
                    </ul>
                </div>
            </div>
            <form class="form-inline">
                    <a class="btn btn-outline-info my-2 my-sm-0" asp-area="" asp-controller="Account" asp-action="Index">Login</a>
                </form>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-light">
            &copy; 2022 - Supplier App - <a asp-area="" asp-controller="Supplier" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap4.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.bootstrap4.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.print.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.colVis.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/latihan.js"></script>
    <script src="~/js/trial.js"></script>
    <script src="~/js/Product.js"></script>
    <script src="~/js/Supplier.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

aspnet31/Views/Shared/_LayoutAdministrator.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>@ViewData["Title"] - First ASP .NET</title>

  <!-- Custom fonts for this template-->  
  <link href="~/Dashboard/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="~/Dashboard/css/sb-admin-2.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/2.2.3/css/buttons.dataTables.min.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  
  <link rel="stylesheet" href="~/css/sweetalert2.min.css">
  <link rel="stylesheet" href="~/css/site.css" />
  <link rel="stylesheet" href="~/css/latihan.css" />
  <link rel="stylesheet" href="~/css/Dashboard.css" />

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="https://localhost:44321/">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">First Web</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="https://localhost:44321/Dashboard">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <div class="sidebar-heading">
        Contents
      </div>
            
            @*@if (User.IsInRole("Staff"))
            {
              <li class="nav-item active">
                <a class="nav-link" href="https://localhost:44321/Supplier">
                  <i class="fas fa-fw fa-table"></i>
                  <span>Supplier</span></a>
              </li>
            }

            @if (User.IsInRole("Manager"))
            {
              <li class="nav-item active">
                <a class="nav-link" href="https://localhost:44321/Product">
                  <i class="fas fa-fw fa-table"></i>
                  <span>Product</span></a>
              </li>
            }*@
      <li class="nav-item active">
        <a class="nav-link" href="https://localhost:44321/Supplier">
          <i class="fas fa-fw fa-table"></i>
          <span>Supplier</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="https://localhost:44321/Product">
          <i class="fas fa-fw fa-table"></i>
          <span>Product</span></a>
       </li>

      <li class="nav-item active">
        <a class="nav-link" href="https://localhost:44321/Latihan">
          <i class="fas fa-fw fa-table"></i>
          <span>Pokemon</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>


            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Kei Shiraishi</span>
                <img class="img-profile rounded-circle" src=https://kokujapan.com/wp-content/uploads/2020/11/aramajapan.com-mai-shiraishi-has-graduated-from-nogizaka46-mai-shiraishi-has-graduated-from-nogizaka46.png">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" @*data-toggle="modal" data-target="#loginModal"*@ href="https://localhost:44321/account">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Login
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-dark">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
            <a href="https://localhost:44321/Home/Privacy">- Privacy</a>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Login Modal-->
  <div id="loginModal" class="modal fade">
		<div class="modal-dialog modal-login">
			<div class="modal-content">
				<div class="modal-header">				
					<h4 class="modal-title">Member Login</h4>
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<div class="modal-body">
					<form class="loginForm" action="/examples/actions/confirmation.php" method="post">
						<div class="form-group">
							<i class="fa fa-user"></i>
							<input type="text" id="usernameLogin" class="form-control" placeholder="Username" required="required">
						</div>
						<div class="form-group">
							<i class="fa fa-lock"></i>
							<input type="password" id="passwordLogin" class="form-control" placeholder="Password" required="required">					
						</div>
						<div class="form-group" id="submitLogin">
							<input type="submit" class="btn btn-primary btn-block btn-lg" value="Login">
						</div>
					</form>
				</div>
				<div class="modal-footer">
					<a href="#">Forgot Password?</a>
				</div>
			</div>
		</div>
	</div> 

  <!-- Bootstrap core JavaScript-->
  <script src="~/Dashboard/vendor/jquery/jquery.min.js"></script>
  <script src="~/Dashboard/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="~/Dashboard/vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="~/Dashboard/js/sb-admin-2.min.js"></script>

  <!-- Page level plugins -->
  <script src="~/Dashboard/js/sb-admin-2.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap4.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.bootstrap4.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.html5.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.print.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.2.3/js/buttons.colVis.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <!-- Page level custom scripts -->
  <script src="~/Dashboard/js/demo/chart-area-demo.js"></script>
  <script src="~/Dashboard/js/demo/chart-pie-demo.js"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  <script src="~/js/latihan.js"></script>
  <script src="~/js/Supplier.js"></script>
  <script src="~/js/Product.js"></script>
  @*<script src="~/js/trial.js"></script>*@
  <script src="~/js/Dashboard.js"></script>

</body>

</html>

aspnet31/Views/Shared/_LayoutLatihan.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - First ASP .NET</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/latihan.css" />
</head>
<style>
    .footer {
    width: 100%;
    font-size: 14px;
    border-top: 1px solid rgba(0,0,0,0.1);
    background: #553C18;
    }
</style>
<body>
    <header>
       @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item"> 
                            <a class="nav-link text-light" asp-area="" asp-controller="Supplier" asp-action="Index">Supplier</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Latihan" asp-action="Index">Latihan</a>
                        </li>
                    </ul>
                </div>
            </div>
            <form class="form-inline">
                    <a class="btn btn-outline-info my-2 my-sm-0" asp-area="" asp-controller="Account" asp-action="Index">Login</a>
                </form>
        </nav>*@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container text-light">
            &copy; 2022 - Supplier App - <a asp-area="" asp-controller="Supplier" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/latihan.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>